server:
  port: 8080
  ip: 118.25.182.144
spring:
  application:
    name: shop
  #数据源
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${server.ip}:3306/shop?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #阿里巴巴连接池
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet:  #访问监控网页的登录用户名和密码,依赖版本1.1.10   过高这个监控页面显示不出来
        login-username: druid
        login-password: druid

  data:
    solr:
      host: http://${server.ip}:8983/solr/solrhome

  redis:
    database: 0
    host: ${server.ip}
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-wait: 1
        max-idle: 10
        min-idle: 0
    timeout: 1000

  rabbitmq:
    host: ${server.ip}
    port: 5672
    username: learn
    password: 123456
    virtual-host: /learn
    publisher-returns: true #消息确认
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
    template:
      mandatory: true
    listener:
      direct:
        acknowledge-mode: manual

  mvc:
    static-path-pattern: /static/**

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  resources:
    #释放静态资源
    static-locations: classpath:/static/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-statement-timeout: 8
  mapper-locations: classpath:/mapper/*/*.xml
  type-aliases-package: com.learn.shop.entity.*.*
  global-config:
    db-config:
      logic-delete-field: deleteStatus  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: ${server.ip}:22122
#  自定义图片前路径
images:
  url:
    pre: http://${server.ip}:8888/
redis:
  expire:
    timeout: 3600
  pre:
    product: ${spring.application.name}:pre
weChat:
  token: 123456
