server:
  port: 8080
spring:
  #数据源
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.249.133:3306/mall?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #阿里巴巴连接池
    druid:
      initial-size: 5                                             #连接池初始化大小
      min-idle: 10                                                #最小空闲连接数
      max-active: 20                                              #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet:                                          #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-statement-timeout: 8
  mapper-locations: classpath:/mapper/*/*.xml
  type-aliases-package: com.learn.shop.entity.*.*
  global-config:
    db-config:
      logic-delete-field: deleteStatus  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.249.140:22122